### ISSUE TITLE
TypeScript bindings

### ISSUE THREAD

**Issue by dennismphil** [anephenix/sarus#10]
Thanks for the excellent documentation and great project. Would be great if the TypeScript bindings can also be published

**Comment by paulbjensen** [comment]
Hi @dennismphil, ok, I'll have a look at that tomorrow.

**Comment by paulbjensen** [comment]
Hi,

It is currently a work in progress, but it should hopefully be ready by Monday.

https://github.com/anephenix/sarus/tree/feature/typescript

**Comment by paulbjensen** [comment]
Hi,

I've got a version of Sarus with the TypeScript bindings, and the codebase has been converted to TypeScript* (* - the caveat is that strictMode is set to false in the tsconfig.json).

This is the first time I've converted an existing project to TypeScript from scratch, so if there's any tips or feedback about the conversion, I'm all ears.

I think that should it be good, this could be released as a 0.3.0 version. Then I can focus on applying strict mode typescript in a 2nd pass.

**Comment by paulbjensen** [comment]
@dennismphil

**Comment by dennismphil** [comment]
Sounds like a good approach. Thank you.

Will test this out

**Comment by dennismphil** [comment]
Took a quick first pass through the code. Looks great to me. Thank you.

In order to enable strict mode on, you could consider replacing some of the `any` -> `unknown` which might help. Overall great code!

![](https://render.bitstrips.com/v2/cpanel/5ac82034-71ae-4bef-a427-d437206edd89-27f3d64a-b3a3-43b8-a269-f9caa01ea0d8-v1.png?transparent=1&palette=1&width=246)

**Comment by paulbjensen** [comment]
Hi @dennismphil,

Sorry for the delay. Sarus version 0.3.0 has been released with the TypeScript conversion. Enjoy.

Paul
