### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by dennismphil** [anephenix/sarus#14]
**Describe the bug**
When I installed `v0.3.0`, I am getting an error in my Jest tests:
```
/node_modules/@anephenix/sarus/dist/index.js:2
    import { WS_EVENT_NAMES, DATA_STORAGE_TYPES } from "./lib/constants";
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```

A helpful [link](https://xperimentalhamid.com/how-do-i/fix-cannot-use-import-statement-outside-a-module/)

**Comment by paulbjensen** [comment]
Ah, yes. I ran into this issue (not with Sarus but another library).

We could include ```"type":"module"``` in the package.json file. I'll test out if that option works.

**Comment by paulbjensen** [comment]
Got this branch which has the proposed change in: https://github.com/anephenix/sarus/tree/bug/14-cannot-use-import-statement-outside-module

**Comment by paulbjensen** [comment]
Hi Dennis, 

I've also switched the TypeScript compilation options to output the module as a ES2015 module rather than an ESnext module.

Could you give it a try, or if you have an example snippet of code to replicate the error you encountered, provide that somewhere? Thanks.

**Comment by paulbjensen** [comment]
Ok I can replicate the error. Will find a way to resolve it.

**Comment by paulbjensen** [comment]
Version 0.3.1 has been published

**Comment by dennismphil** [comment]
Thank you. Confirming this issue is resolved.

**Comment by paulbjensen** [comment]
Thanks @dennismphil. I think at some point I will add an integration test using Cucumber and Puppeteer to test the WebSocket library so that I can avoid issues like this one cropping up.
