### ISSUE TITLE
please add to support protobuf

### ISSUE THREAD

**Issue by Arstman** [anephenix/sarus#17]
**Is your feature request related to a problem? Please describe.**

yes, since many ws server work with protobuf, i think it might be great if support this.

**Describe the solution you'd like**

right now the original websocket object is a internal property, to support protobuf we need to set the a property of ws :

```javascript
ws. binaryType = 'arraybuffer'
```
therefore may you guy can add one or  more param to the Sarus constructor,  gives us the power to maniputing the ws, perhaps? 
:)

thanks~

**Comment by paulbjensen** [comment]
Hello.

Sorry for the delay in replying to your request. I've added a feature to Sarus to enable you to set the binaryType on the WebSocket, like this:

```javascript
const sarus = new Sarus({
    url: 'wss://ws.anephenix.com',
    binaryType: 'arraybuffer'
});
```

@anephenix/sarus version 0.3.2 has been published and includes this feature.

Let me know if you run into any issues.

Regards,

Paul Jensen

**Comment by paulbjensen** [comment]
@Arstman is it all good?

**Comment by paulbjensen** [comment]
Will close now.
