### ISSUE TITLE
Event listener garbage collection

### ISSUE THREAD

**Issue by paulbjensen** [anephenix/sarus#2]
We are seeing an issue in Google Chrome whereby event listener functions that were attached to an existing WebSocket connection are not being garbage collected when the WebSocket connection is severed and closed.

This leads to an incremental buildup in the number of event listeners that exist in the web page's memory over time. The number of event listeners stops incrementing once a WebSocket connection is established.

Here is a screenshot of what I see happening in the Google Chrome DevTools:

<img width="1272" alt="Screenshot 2019-03-10 at 08 53 04" src="https://user-images.githubusercontent.com/3840/54082263-d1cf3200-4312-11e9-984b-91d20f64a3cc.png">

**Comment by paulbjensen** [comment]
I've been able to establish that the WebSocket event listeners are not getting cleaned up as desired, and that they can still trigger, even though the originating WebSocket instance has been overwritten.

To replicate this, visit https://sarus-client-logger.netlify.com/ (in Google Chrome):

Step 1 - Seconds later, type in "wss://non-existent.com", and press Enter
Step 2 - Type in "wss://echo.websocket.org" and press Enter

What will happen is that even though a successful connection to echo.websocket.org has been established, the reconnection attempts to wss://non-existent.com will continue, because the event listeners that attempt to reconnect on a failed WebSocket connection continue to exist.

The Sarus client logger has been helpful in illustrating this behaviour.

**Comment by alevor657** [comment]
Is this a good place to use [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef)?

**Comment by paulbjensen** [comment]
Possibly. I haven't used WeakRef before but from what I read in the docs it has to be used carefully.

I will look into it.

**Comment by simlevesque** [comment]
is this still an issue ? can it be solved ? I'm looking into using sarus embeded devices so I don't want any blatant memory safety issue. Thank you.

**Comment by paulbjensen** [comment]
@simlevesque I'll take a look into it after work.

**Comment by paulbjensen** [comment]
@simlevesque published Sarus 0.4.2. It will remove eventListeners from a closed WebSocket instance before attempting to replace it with a new WebSocket instance upon reconnect.

https://www.npmjs.com/package/@anephenix/sarus

If you are planning on using Sarus in a Node.js server-side context, you may also want to look at Hub - http://github.com/anephenix/hub

**Comment by paulbjensen** [comment]
Closing.

**Comment by simlevesque** [comment]
Thank you !
