### ISSUE TITLE
DOMException stacktrace gets lost when initializing Sarus with bogus URL

### ISSUE THREAD

**Issue by justuswilhelm** [anephenix/sarus#370]
**Describe the bug**
When creating a new Sarus instance, providing an invalid URL hides the original stacktrace and fails in a hard to understand way.

**To Reproduce**
1. Create a blank Svelte/whatever starter project
2. In the main app page put:
```svelte
<script lang="ts">
    import Sarus from "@anephenix/sarus";
    new Sarus("bogus-url");
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

```
3. Load in browser (after running npm run dev or similar)
4. Inspect browser console
```
[vite] connecting... client.ts:18:8
[vite] connected. client.ts:150:14
[HMR][Svelte] Failed to rerender <+page> proxy.js:15:11
DOMException: An invalid or illegal string was specified proxy.js:19:13
[vite] hot updated: /src/routes/+page.svelte client.ts:479:12
```

**Expected behavior**
Calling new Sarus() should fail directly

**Desktop (please complete the following information):**
- Firefox-esr 102.15.0esr
- Sarus: 0.4.6

**Comment by paulbjensen** [comment]
Hi @justuswilhelm,

Agreed, the message `An invalid or illegal string was specified` for the WebSocket url is vague.

I will look to add a validation step before instantiating the WebSocket instance that will validate the url, and report a more understandable error message in case the url isn't valid.

**Comment by justuswilhelm** [comment]
So trying to write a test case like this:

```
  it("handles an invalid websocket url cleanly", () => {
    const sarus: Sarus = new Sarus({ url: "bogus-url"});
  });
```

gives me a very different error:

```
    SyntaxError: Failed to construct 'WebSocket': The URL's scheme must be either 'ws' or 'wss'. 'http:' is not allowed.

      267 |    */
      268 |   connect() {
    > 269 |     this.ws = new WebSocket(this.url, this.protocols);
          |               ^
      270 |     this.setBinaryType();
      271 |     this.attachEventListeners();
      272 |     if (this.messages.length > 0) this.process();

      at urlVerification (node_modules/mock-socket/dist/mock-socket.js:1405:11)
      at new WebSocket (node_modules/mock-socket/dist/mock-socket.js:1463:16)
      at Sarus.connect (src/index.ts:269:15)
      at new connect (src/index.ts:170:10)
      at Object.<anonymous> (__tests__/index/connectionOptions.test.ts:22:26)
```

This is actually great, there is a real stacktrace. But the problem is that this is happening with a mock socket. For some reason using my browser's (Firefox) websocket implementation causes it to fail __without a stacktrace__ at a completely different location.

Side question: I was trying to figure out if I could reproduce this issue using jsfiddle, but I couldn't load the package correctly using unpkg (even when appending ?module), using ESM import syntax. Any idea on a minimal example that can new Sarus() correctly on jsfiddle or codepen? It would really help making a minimally reproducible example.

Unfortunately I don't see how using mock-sockets to test validation as an approach would work, so my idea up there is not getting me far. What would get me further is understanding why (at in least Firefox) the thing just fails silently.

**Comment by justuswilhelm** [comment]
Additional comment:

I wanted to make sure I write some functions that call each other to see if I can't get a stacktrace somehow (post-dinner 10PM logic) with this svelte page

```
<script lang="ts">
  import {onMount} from "svelte";
  import Sarus from "@anephenix/sarus";
  function makeSarus(): Sarus {
    return new Sarus({ url: "bogus-url"});
  }

  function action() {
    console.log("Constructing sarus");
    const sarus = makeSarus();
    console.log(sarus);
  }

  onMount(() => {
    action();
  });
</script>
<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>
```

And there is no stacktrace that says either makeSarus() or action(). See the attached screenshot:

![sarus](https://github.com/anephenix/sarus/assets/1641042/278533ad-2dcf-4cd8-900c-81c888e04fa2)


There is a test repo branch with this code [here](https://github.com/jwp-consulting/svelte-test-bed/tree/sarus-test)

It could also all just be because of Vite / Svelte / SvelteKit...

**Comment by paulbjensen** [comment]
One possible way to approach it is to modify this function:

https://github.com/anephenix/sarus/blob/78de640c9ee281dd54d231f964ef9c59de67590c/src/index.ts#L268-L272

So that before it instantiate a new `Websocket` instance, it will check that the url is valid, and if it isn't, throw an error with an error message that is much better to understand, much like what MockSocket did with their error message.`

I would write a message like "WebSocket url is invalid. Make sure that the url begins with the correct protocol (ws:// or wss:// e.g. ws://chat.example.com or wss://secure-chat.example.com)" 

That will mean that we can help guide the user a bit better in terms of understanding what is going on as well as how to resolve it.

**Comment by justuswilhelm** [comment]
Thank you for the detailed guidance here. I have created a pull request. (See #375 )

Furthermore, I am almost certain that Svelte is the culprit on the drowning DOMError here. Issuing a regular Error here should resolve this. (Not that we have to cater to Svelte problems here specifically ;)
